import RootLayout from "@/components/Layouts/RootLayout";
import Head from "next/head";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>PC Builder | Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>home page</h1>
      </main>
    </>
  );
}

HomePage.getLayout = function getLayout(page) {
  return <RootLayout>{page}</RootLayout>;
};
